### ISSUE TITLE
Error using KirikiriUnenecryptedArchive

### ISSUE THREAD

**Issue by Rinyuu** [arcusmaximus/KirikiriTools#1]
Hey guys, first of all, great work!

I have a problem with the UnencryptedArchive.tpm patch. (I'm a huge noob with stuff like this, so maybe it's me who's doing something wrong.) The game I'm trying to mod is Love3 -love cube- (Demo).

I couldn't find a tpm file in the folders I downloaded from here, so I compiled them in VisualStudio. After that I got a "1KirikiriUnencryptedArchive.tpm" file. I placed that in the plugin folder, but I keep getting this error: 

Access Violation: The thread attempts to read from or write to a virtual adress for which it does not have access.

I tried all the basic stuff like launching as Admin, and compatebility settings and such, but can't seem to get past this error... I also tried the ArchiveLauncher.exe, in case the game has CxDex ( which I doubt, because there already was 1 tpm file in the games plugin folder: xp3dec.tpm) but then i get this error:

Script exeption raised.
Cannot convert given narrow string to wide string.

Any ideas?

**Comment by arcusmaximus** [comment]
KirikiriUnencryptedArchive had some problems on Windows 10, causing it not to work there. There's now an updated version that does work.
