### ISSUE TITLE
Error extracting trial version of upcoming games

### ISSUE THREAD

**Issue by fushi002** [arcusmaximus/KirikiriTools#10]
[Vndb](https://vndb.org/v30458)
[Link](https://www.dlsite.com/maniax/circle/profile/=/maker_id/RG41088.html)
[Direct Download](https://trial.dlsite.com/doujin/RJ394000/RJ393720_ana_trial.zip)

With this tool, data was extracted in real time to decrypt the trial version of the above link game.
Pimg, Scn files are extracted normally, but some files were extracted abnormally (for example, appconfig.tjs)
Maybe, some TJS2 file header is corrupted.
I will be very grateful if you update the tool.

**Comment by arcusmaximus** [comment]
If the other files are extracted correctly, the .tjs files should be too. However, .tjs files may be compiled to binary code (Wamsoft often does this). You can see if a file is compiled by checking whether it starts with the text "TJS2".

**Comment by fushi002** [comment]
Surprisingly, only a few are extracted normally.
For example, the Override.tjs file is extracted normally.
(Header exists starting with TJS2100)
![image](https://user-images.githubusercontent.com/88200209/174260602-02b5cac6-a303-48af-9abf-bc922d62fa65.png)


However, some files are not extracted normally.
Below is part of config.tjs.
![image](https://user-images.githubusercontent.com/88200209/174260715-e391a527-65bb-4623-b93d-745c8b034497.png)


All image files are extracted normally.
However, some types of files seem to be the problem.

This is not the only problem.
After the translation, we also need a method to apply it to the game normally.
The universal patch of krkrextract that I always use is also unavailable, so I have to find another way.
It would be great if I could get some help on this.

**Comment by arcusmaximus** [comment]
config.tjs is scrambled rather than compiled. Please see the description of the "KirikiriDescrambler" tool in the README.

For applying patched files to the game, please read the description of "KirikiriUnencryptedArchive" fully.

**Comment by fushi002** [comment]
Thank you for your help
I was a fool :3
