### ISSUE TITLE
Update for version.dll

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/KirikiriTools#12]
Can you add [this](https://github.com/sst311212/FuckBootStrap) to version.dll? It's for running new krkrz without this pop up
![image](https://user-images.githubusercontent.com/81801486/184654532-7a972a8c-7754-4d59-bd26-6829a965a1d4.png)

**Comment by Cosetto** [comment]
Wait nevermind, the game just runs normally with version.dll. Am I having deja vu or something because the last time I tried it didn't work

**Comment by arcusmaximus** [comment]
The DLL is indeed already quite sneaky and built to avoid this detection.
