### ISSUE TITLE
Work on Linux

### ISSUE THREAD

**Issue by makcimbx** [arcusmaximus/KirikiriTools#14]
I tried the version.dll on Steam Deck with most versions of Proton, but with this dll the game does not start. Im trying to use forked GARbro with ATRI -My Dear Moments- for unpack xp3 (that worked), translate and then pack to xp3,  but I didn't see any difference in game. WIth version.dll and pack with Xp3Pack from this tools everything working fine on Windows, but linux with proton when version.dll in game folder cant run game.

**Comment by arcusmaximus** [comment]
If it works on Windows, I'd say this is a problem in Proton, not in version.dll. (Same situation as a console game that doesn't work in an emulator - surely you'd blame the emulator in that case, not the game.)

Please create a Wine ticket instead.
