### ISSUE TITLE
`version.dll`: Cannot convert the variable type ((void) to Object)

### ISSUE THREAD

**Issue by yescallop** [arcusmaximus/KirikiriTools#18]
When using `version.dll` to extract .xp3 archives shipped with *ATRI -My Dear Moments- (Steam version)*, the game failed to start and an information dialog popped up saying `Cannot convert the variable type ((void) to Object)` (screenshot attached below).

I provide a debug log that might help locate the source of the problem: [debug.log](https://github.com/arcusmaximus/KirikiriTools/files/11202626/debug.log)

![image](https://user-images.githubusercontent.com/16952958/231222291-836aa5fa-cf21-4276-b47f-1f83c1ca8f41.png)

**Comment by Cosetto** [comment]
> When using `version.dll` to extract .xp3 archives shipped with _ATRI -My Dear Moments- (Steam version)_, the game failed to start and an information dialog popped up saying `Cannot convert the variable type ((void) to Object)` (screenshot attached below).
> 
> I provide a debug log that might help locate the source of the problem: [debug.log](https://github.com/arcusmaximus/KirikiriTools/files/11202626/debug.log)
> 
> ![image](https://user-images.githubusercontent.com/16952958/231222291-836aa5fa-cf21-4276-b47f-1f83c1ca8f41.png)

Nope, Atri is not Wamsoft's encryption, so it won't work
Instead, use [krkrextract](https://github.com/xmoezzz/KrkrExtract) or [GARbro mod](https://github.com/crskycode/GARbro)
When using GARbro mod, choose "Atri" encryption scheme
![image](https://user-images.githubusercontent.com/81801486/231405197-15f03df4-b553-4a01-bbc1-2b13a77782ee.png)

**Comment by yescallop** [comment]
@Cosetto Thank you! I looked into this a bit and now believe that this is a bug in the code.

This is caused by the patcher indiscriminately redirecting all storage media, including `steam`:

```
00000220	3.46347475	[4700] Redirecting steam://./savecheck to file://./d/Program Files (x86)/Steam/steamapps/common/ATRI -My Dear Moments-/unencrypted/savecheck	
00000221	3.46351171	[4700] Redirecting steam://./savecheck to file://./d/Program Files (x86)/Steam/steamapps/common/ATRI -My Dear Moments-/unencrypted/savecheck
```

Which can be fixed by changing the code to not hook the storage media `steam`.

However, after fixing this problem, another problem arised when I tried to press start button in the game (see the following screenshot):

![Screenshot](https://user-images.githubusercontent.com/16952958/231422991-7ec4edc5-fa23-49da-84f5-d063114b29f4.png)

Which seems to result from the patcher failing to extract the file `archive://data.xp3/image/bgmtitle/tw/bgmtitle_bgm01_tw.png` when the folder `unencrypted/image/bgmtitle/tw` cannot be created because `Directory::Create` isn't recursive and its parent folder wasn't created beforehand.

I'll open a PR that fixes these two bugs soon.

**Comment by Cosetto** [comment]
> @Cosetto Thank you! I looked into this a bit and now believe that this is a bug in the code.
> 
> This is caused by the patcher indiscriminately redirecting all storage media, including `steam`:
> 
> ```
> 00000220	3.46347475	[4700] Redirecting steam://./savecheck to file://./d/Program Files (x86)/Steam/steamapps/common/ATRI -My Dear Moments-/unencrypted/savecheck	
> 00000221	3.46351171	[4700] Redirecting steam://./savecheck to file://./d/Program Files (x86)/Steam/steamapps/common/ATRI -My Dear Moments-/unencrypted/savecheck
> ```
> 
> Which can be fixed by changing the code to not hook the storage media `steam`.
> 
> However, after fixing this problem, another problem arised when I tried to press the start button in the game (see the following screenshot):
> 
> ![Screenshot](https://user-images.githubusercontent.com/16952958/231422991-7ec4edc5-fa23-49da-84f5-d063114b29f4.png)
> 
> Which seems to result from the patcher failing to extract the file `archive://data.xp3/image/bgmtitle/tw/bgmtitle_bgm01_tw.png` when the folder `unencrypted/image/bgmtitle/tw` cannot be created because `Directory::Create` isn't recursive and its parent folder wasn't created beforehand.
> 
> I'll open a PR that fixes these two bugs soon.

No man, he made it to extract game with Wamsoft encryption only. I remember he said if you can extract the game with another tool, then there's no point to do that.

**Comment by yescallop** [comment]
I understand your point and indeed GARbro worked very well for my use case, but I feel that these bugs are so generic that people may run into them sooner or later, even with games that use Wamsoft encryption :P

**Comment by Cosetto** [comment]
Does it have bug on Wamsoft? If it's a yes, it will be great if you can fix. I have only seen people use this to translate games with CxCrypt, I mean there's no point of extracting file by file of CxCrypt when we have other tools to extract all at once

**Comment by yescallop** [comment]
Yes, I get your point. Perhaps someone can try the tool out with their games from Steam that use Wamsoft encryption. I would expect the same result if the game also utilizes Steam API for cloud storage.

**Comment by Cosetto** [comment]
Actually, you can remove the embed things of steam in the exe like this
![image](https://user-images.githubusercontent.com/81801486/231473699-ca8a74b1-747b-4e5f-8b5c-8c4480d99e00.png)
Then others tool will work fine

**Comment by arcusmaximus** [comment]
> No man, he made it to extract game with Wamsoft encryption only.

I didn't, really. The feature was indeed originally made for dealing with recent Wamsoft games, but that doesn't mean it's limited to those. The extraction method is completely generic and independent of the specific encryption used.

@yescallop Thank you for the PR.
