### ISSUE TITLE
narrow string to wide string

### ISSUE THREAD

**Issue by vikas2316** [arcusmaximus/KirikiriTools#2]
I have tried lots of tools to repack xp3 (garbro, krkrExtract, etc). KrKrExtract and KiriKiriTools creates patch xp3 but when I place it in folder game gives me this error "cannot convert narrow string to wide string", Garbro tells me it couldn't find the file I am archiving, I don't have much experience regarding repacking and modding xp3 files but please can someone help me explain how to do this correctly?
game : https://vndb.org/v24275

**Comment by UserUnknownFactor** [comment]
Try code from GH-3, some games won't work with utf-8 files.

**Comment by arcusmaximus** [comment]
The game uses a decryption method that wasn't caught by the tool. As a result, it tried to decrypt your unencrypted files, resulting in invalid text.

With the new version of the tool, everything should work fine.
