### ISSUE TITLE
Is it possible to force kirikiri games to use unpacked script files?

### ISSUE THREAD

**Issue by UserUnknownFactor** [arcusmaximus/KirikiriTools#4]
I mean in a native generic way. If not, can you, please, make an interceptor for game `read` operations that reads from external file instead of .xp3 and fallback to reading from .xp3 if the external file doesn't exist.

For example if game tries to read from `scenario\script1.ks` inside `data.xp3` it will redirect `read` operation to `.\data\scenario\script1.ks` file.

**Comment by uyjulian** [comment]
There is universal patch exists that will redirect read request. https://github.com/xmoeproject/KrkrExtract

**Comment by UserUnknownFactor** [comment]
From a first glance it seems rather complex system though. 
Some questions here:
In what cases can it work without generating KrkrExtract.db?
Does it fallback to .xp3 if file does not exist?
What is `Game.bin` opened in KrkrFile.dll?
