### ISSUE TITLE
game crash after close when use Locale.Emulator with jap language

### ISSUE THREAD

**Issue by bynejake** [arcusmaximus/KirikiriTools#5]
As the title says, some games must be started in Japanese.

The running process is normal, but it will crash after closing the game

![QQ截图20211130042823](https://user-images.githubusercontent.com/73972648/143938255-27b70a37-9733-40c6-9df8-f2366f9cbac2.png)

**Comment by bynejake** [comment]
This only happens when some games can load patches without requiring version.dll，and put the version.dll in game, it wil crash when close the game.

**Comment by arcusmaximus** [comment]
> This only happens when some games can load patches without requiring version.dll，and put the version.dll in game, it wil crash when close the game.

Not sure I understand the issue. If the game can load custom .xp3 files without the version.dll, why put it in the game folder at all?

Also, are you using the latest version of the locale emulator?

**Comment by bynejake** [comment]
> > This only happens when some games can load patches without requiring version.dll，and put the version.dll in game, it wil crash when close the game.
> 
> Not sure I understand the issue. If the game can load custom .xp3 files without the version.dll, why put it in the game folder at all?
> 
> Also, are you using the latest version of the locale emulator?

sorry for last comments, it's not correct, after test DRAWSOFT's games, 2 game has issue:

> ムチムチデカパイマラ喰い魔王様とおんぼろ四畳半同棲生活

- ムチムチデカパイマラ喰い魔王様とおんぼろ四畳半同棲生活.exe：
   Need version.dll & **No need LE in JP**

1. can not run game again after close game, there will be a residual process that prevents the game from restarting.
2. **LE in JP**, crash after close game.

- ムチムチデカパイマラ喰い魔王様とおんぼろ四畳半同棲生活.exe → offical patch maousama.exe：
   Need version.dll & **Need LE in JP**：crash after close game.

> 催眠アイドロップス 
   Need version.dll & **Need LE in JP**：crash after close game

may version.dll leak memory or something（just guess）

**Comment by arcusmaximus** [comment]
Should be fixed with the 1.3 release.

**Comment by bynejake** [comment]
fixed, thanks
