### ISSUE TITLE
Support for new KiriKiriZ version with more complex protection

### ISSUE THREAD

**Issue by MishaIac** [arcusmaximus/KirikiriTools#8]
Hi. I would like to know if there will be support for the new version of KiriKiriZ, where more complex protection? GARbro and KrkrExtract can't put translation in this version of KiriKiriZ. Because of this protection, xmoe will [not update](https://github.com/xmoeproject/KrkrExtract/issues/129) KrkrExtract and GARbro is abandoned. So, I will be very grateful if you can add support KirikiriUnencryptedArchive for this engine version.

Some VNs on this engine version:
[花鐘カナデ＊グラム Chapter:1 小桜結](https://vndb.org/v30969)
[七ヶ音学園 -旅行部-](https://vndb.org/v32820)

**Comment by MishaIac** [comment]
Solved.

**Comment by Sisulizer** [comment]
@MishaIac can you tell how? I want to try to make unencrypted archive for [this](https://vndb.org/r87729), I think it used the new version of krkrz too

**Comment by arcusmaximus** [comment]
Support is now available. See the updated README for details.

**Comment by Cosetto** [comment]
> > Support is now available. See the updated README for details.
> 
> Sorry, but is "KirikiriUnencryptedArchive" and "KrkrzExtract" only way? I want every(+unused data) files.

then use [krkrextract](https://github.com/xmoeproject/KrkrExtract) or GARbro

**Comment by MishaIac** [comment]
> > Support is now available. See the updated README for details.
> 
> Sorry, but is "KirikiriUnencryptedArchive" and "KrkrzExtract" only way? I want every(+unused data) files.

Everyone wants to extract all files, but at the moment, only this method works with the new KiriKiriZ protection

**Comment by fkvldh** [comment]
> > > Support is now available. See the updated README for details.
> > 
> > 
> > Sorry, but is "KirikiriUnencryptedArchive" and "KrkrzExtract" only way? I want every(+unused data) files.
> 
> then use [krkrextract](https://github.com/xmoeproject/KrkrExtract) or GARbro

I'm sorry. I already tried, but failed.

**Comment by fkvldh** [comment]
> > > Support is now available. See the updated README for details.
> > 
> > 
> > Sorry, but is "KirikiriUnencryptedArchive" and "KrkrzExtract" only way? I want every(+unused data) files.
> 
> Everyone wants to extract all files, but at the moment, only this method works with the new KiriKiriZ protection

Someone said. you know how to use it?
[This one extract perfect.No need to play whole game
https://github.com/Kerisa/ExtractGames/tree/master/kirikiri]

**Comment by MishaIac** [comment]
> > > > Support is now available. See the updated README for details.
> > > 
> > > 
> > > Sorry, but is "KirikiriUnencryptedArchive" and "KrkrzExtract" only way? I want every(+unused data) files.
> > 
> > 
> > Everyone wants to extract all files, but at the moment, only this method works with the new KiriKiriZ protection
> 
> Someone said. You know how to use it? [This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri ]

It is better to use [KrkrExtract](https://github.com/xmoeproject/KrkrExtract). If it does not work, KirikiriUnencryptedArchive is the only way.

**Comment by Cosetto** [comment]
https://rewizzc.blogspot.com/2022/07/a-tutorial-to-dump-kinkoi-golden-time.html
@fkvldh

**Comment by fkvldh** [comment]
> > > > > Support is now available. See the updated README for details.
> > > > 
> > > > 
> > > > Sorry, but is "KirikiriUnencryptedArchive" and "KrkrzExtract" only way? I want every(+unused data) files.
> > > 
> > > 
> > > Everyone wants to extract all files, but at the moment, only this method works with the new KiriKiriZ protection
> > 
> > 
> > Someone said. You know how to use it? [This one extract perfect.No need to play whole game https://github.com/Kerisa/ExtractGames/tree/master/kirikiri ]
> 
> It is better to use [KrkrExtract](https://github.com/xmoeproject/KrkrExtract). If it does not work, KirikiriUnencryptedArchive is the only way.

Thank you.

**Comment by Cosetto** [comment]
@fkvldh good news, looks like my friend has bypass new Wamsoft encryption
![image](https://user-images.githubusercontent.com/81801486/189486054-54bfd5b1-2890-46a5-b9cc-617051e6529c.png)
Looks like the files' name are not in the archive but he will handle it somehow 
![image](https://user-images.githubusercontent.com/81801486/189486111-7b7c636e-e203-4181-bf57-a71258340099.png)

**Comment by MishaIac** [comment]
I guess the protection system there is the same as before, just Wamsoft hashed the file names, that's all. The fact that Crsky added support is of course good, however, the method to get the file names will be the same as the file dump. It turns out that this way you can not find out the names of files that are not used in the game. Also do not forget that Wamsoft almost all the new games with the new protection removed patch system, because of which still will need to use hooks.

**Comment by marcussacana** [comment]
> https://rewizzc.blogspot.com/2022/07/a-tutorial-to-dump-kinkoi-golden-time.html @fkvldh

the link is dead, do you still have the notes of that post or have the patched cxdec for analyze?
I know we can use the tool of this repo, I just want learn what they did it.

**Comment by Cosetto** [comment]
> > https://rewizzc.blogspot.com/2022/07/a-tutorial-to-dump-kinkoi-golden-time.html @fkvldh
> 
> the link is dead, do you still have the notes of that post or have the patched cxdec for analyze? I know we can use the tool of this repo, I just want learn what they did it.

It's a video about bypassing the cxdec to use dumper, but it's not all-in-one extract
[Alternative video](https://www.bilibili.com/video/BV175411S7Au/?spm_id_from=333.999.0.0&vd_source=095531bf7c02440924435d45aa8c2803)
The new version.dll can bypass the cxdec if you don't know

**Comment by marcussacana** [comment]
> > > https://rewizzc.blogspot.com/2022/07/a-tutorial-to-dump-kinkoi-golden-time.html @fkvldh
> > 
> > 
> > the link is dead, do you still have the notes of that post or have the patched cxdec for analyze? I know we can use the tool of this repo, I just want learn what they did it.
> 
> It's a video about bypassing the cxdec to use dumper, but it's not all-in-one extract [Alternative video](https://www.bilibili.com/video/BV175411S7Au/?spm_id_from=333.999.0.0&vd_source=095531bf7c02440924435d45aa8c2803) The new version.dll can bypass the cxdec if you don't know and another [tool](https://github.com/sst311212/FuckBootStrap)

Good, is something like that video that I wanted, I really don't want extract, I want see what has been done to patch the cxdec checks, do you have that video in high resolution? I'm not a chinese to have an account and watch in good quality

**Comment by Cosetto** [comment]
> > > > https://rewizzc.blogspot.com/2022/07/a-tutorial-to-dump-kinkoi-golden-time.html @fkvldh
> > > 
> > > 
> > > the link is dead, do you still have the notes of that post or have the patched cxdec for analyze? I know we can use the tool of this repo, I just want learn what they did it.
> > 
> > 
> > It's a video about bypassing the cxdec to use dumper, but it's not all-in-one extract [Alternative video](https://www.bilibili.com/video/BV175411S7Au/?spm_id_from=333.999.0.0&vd_source=095531bf7c02440924435d45aa8c2803) The new version.dll can bypass the cxdec if you don't know and another [tool](https://github.com/sst311212/FuckBootStrap)
> 
> Good, is something like that video that I wanted, I really don't want extract, I want see what has been done to patch the cxdec checks, @Cosetto, do you have that video in high resolution? I'm not a chinese to have an account and watch in good quality

You can view and download the video [here](https://upos-sz-mirror08ct.bilivideo.com/upgcxcode/36/68/560666836/560666836-1-208.mp4?e=ig8euxZM2rNcNbNgnWdVhwdlhbNHhwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&uipk=5&nbs=1&deadline=1665337698&gen=playurlv2&os=08ctbv&oi=837395164&trid=29a25158d1c74552a999081ac4ac3e6dT&mid=0&platform=html5&upsig=2da735d7879d82363205de2e05fd7e71&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&bw=229880&orderid=0,1&logo=80000000)

**Comment by marcussacana** [comment]
thx

**Comment by Cosetto** [comment]
Crsky has uploaded [new tool](https://github.com/crskycode/GalgameCoding/tree/main/Kirikiri/HxCrypt) to create patch for Wamsoft encryption, though it's a little bit hard to use
