### ISSUE TITLE
Rescramble .dat file 

### ISSUE THREAD

**Issue by tqdungctuct** [arcusmaximus/KirikiriTools#9]
I'm trying to translate Venus Blood GAIA, game is using Kirikiri Engine. I can use KirikiriDescrambler with .dat file (already extract data.xp3) to descramble and view data inside. But when I repack. Game give me error. I think I have to rescramble that file to make it work. Can you give me some advice or some guide to do that. Thank you very much.
Here is the source file

https://mega.nz/file/rIZmRKjT#Xuwt4-_mH-73xV-uVbHfFlF3Dn4pPvUKwDPz_D_jZGk

**Comment by arcusmaximus** [comment]
As mentioned in the README of this repository, rescrambling isn't needed. Instead, the problem is more likely related to .xp3 encryption.

Please try creating an unencrypted .xp3 with the Xp3Pack in this repository, and putting the version.dll in the game folder.

**Comment by tqdungctuct** [comment]
I try to create unencrypted .xp3 but it didn't work. Here is the error game show me
![image](https://user-images.githubusercontent.com/43664956/165004088-62b0da9e-7100-45b1-a84f-d5563a2a6c49.png)

**Comment by arcusmaximus** [comment]
Did you place version.dll in the game folder?
Do you see anything in DebugView?
Have you tried saving first.ks using the UTF-16 LE BOM encoding?

**Comment by tqdungctuct** [comment]
Thank you very much. After encoding with UTF-16 LE BOM. Game is now running. I don't know about this encode until you said. Thank again
